name: Test notebooks
on:
  push:
    branches:
      - ci-for-notebooks

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install jupyter notebook
        run: |
          pip install notebook

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install jupyter deno kernel
        run: deno jupyter --unstable --install

      - name: Run notebook 11
        run: jupyter execute --kernel_name=deno 11_Running_tests.ipynb

      - name: Run notebook 1
        run: jupyter execute --kernel_name=deno 01_Intro.ipynb
